### ISSUE TITLE
screenshot out of date for Add Cluster in Ex1

### ISSUE THREAD

**Issue by dlbewley** [konveyor/labs#13]
Image https://github.com/konveyor/labs/blob/master/mtc/bookbag/workshop/content/screenshots/lab4/mtc-add-cluster.png is not up to date. 

The dialog has a image registry field and looks like this now
https://www.dropbox.com/s/w7o937h69h1sh91/Screen%20Shot%202021-02-17%20at%2014.46.34.png?dl=0

**Comment by pericnenad** [comment]
New screenshot uploaded with some doc text changes as well.
