### ISSUE TITLE
exercise 1 missing step in migration plan

### ISSUE THREAD

**Issue by dlbewley** [konveyor/labs#14]
Image
https://github.com/konveyor/labs/raw/master/mtc/bookbag/workshop/content/screenshots/lab4/mtc-mig-plan-namespaces.png

Shows 5 steps in migration plan.

Current MTC adds '5. Migration Options' to make 6 steps and looks like this now
https://www.dropbox.com/s/3kz7lyb6wir0qbr/Screen%20Shot%202021-02-17%20at%2015.07.07.png?dl=0

**Comment by pericnenad** [comment]
New screenshot added.
