### ISSUE TITLE
phrasing of Migrate dialog has changed

### ISSUE THREAD

**Issue by dlbewley** [konveyor/labs#15]
Text of exercise 1 says

"Optionally choose to not terminate the application on the source cluster. Leave it unchecked and select Migrate."

MTC defaults to Halt now and unchecking means to NOT Halt, in contrast to above text.

It looks like this now

https://www.dropbox.com/s/sgwyojtdku3ebrs/Screen%20Shot%202021-02-17%20at%2015.23.53.png?dl=0

**Comment by pericnenad** [comment]
Fixed in the newest docs and screenshots.
